name: Keep Scheduled Active
on:
  schedule:
    - cron: "0 0 * * 3"  # 毎週水曜 0:00 UTC／日本時間 9:00
permissions:
  actions: write
jobs:
  workflow-keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
