name: Keep Scheduled Active

on:
  schedule:
    - cron: "0 0 * * 3"  # 毎週水曜 0:00 UTC／9:00 JST

permissions:
  actions: write

jobs:
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
