name: Keep Scheduled Active
on:
  schedule:
    - cron: "0 0 * * 0"  # 毎週日曜 00:00 UTC（日本時間では午前9時）の例
permissions:
  actions: write
jobs:
  workflow-keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
